name: Kirim ke ApiSub
on:
  schedule:
    - cron: '0 */23 * * *'
  workflow_dispatch:

jobs:
  run_script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install python-telegram-bot==13.15
          
      - name: Run Python script
        run: |
          python apisub.py  # Replace with your script's path
        
