name: Download APK and Put on Release
on:
  workflow_dispatch:
jobs:
  run:
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
      - name: Install Dependencies
        run: |
          sudo apt install -y curl wget unzip zip

      - name: Download APK
        run: |
          sudo wget "https://github.com/dyhkwong/Exclave/releases/download/0.12.2/Exclave-0.12.2-arm64-v8a.apk"
          sudo wget "https://github.com/dyhkwong/Exclave/releases/download/0.12.2/Exclave-0.12.2-armeabi-v7a.apk"
          sudo wget "https://github.com/dyhkwong/Exclave/releases/download/0.12.2/Exclave-0.12.2-x86.apk"
          sudo wget "https://github.com/dyhkwong/Exclave/releases/download/0.12.2/Exclave-0.12.2-x86_64.apk"
          sudo wget "https://github.com/MatsuriDayo/NekoBoxForAndroid/releases/download/1.2.9/NB4A-1.2.9-arm64-v8a.apk"
          sudo wget "https://github.com/MatsuriDayo/NekoBoxForAndroid/releases/download/1.2.9/NB4A-1.2.9-armeabi-v7a.apk"
          sudo wget "https://github.com/MatsuriDayo/NekoBoxForAndroid/releases/download/1.2.9/NB4A-1.2.9-x86.apk"
          sudo wget "https://github.com/MatsuriDayo/NekoBoxForAndroid/releases/download/1.2.9/NB4A-1.2.9-x86_64.apk"
          sudo wget "https://github.com/MetaCubeX/ClashMetaForAndroid/releases/download/Prerelease-alpha/cmfa-2.11.1-alpha-arm64-v8a-release.apk"
          sudo wget "https://github.com/MetaCubeX/ClashMetaForAndroid/releases/download/Prerelease-alpha/cmfa-2.11.1-alpha-armeabi-v7a-release.apk"
          sudo wget "https://github.com/MetaCubeX/ClashMetaForAndroid/releases/download/Prerelease-alpha/cmfa-2.11.1-alpha-universal-release.apk"
          sudo wget "https://github.com/MetaCubeX/ClashMetaForAndroid/releases/download/Prerelease-alpha/cmfa-2.11.1-alpha-x86-release.apk"
          sudo wget "https://github.com/MetaCubeX/ClashMetaForAndroid/releases/download/Prerelease-alpha/cmfa-2.11.1-alpha-x86_64-release.apk"
          sudo wget "https://github.com/2dust/v2rayNG/releases/download/1.8.39/v2rayNG_1.8.39_arm64-v8a.apk"
          sudo wget "https://github.com/2dust/v2rayNG/releases/download/1.8.39/v2rayNG_1.8.39_armeabi-v7a.apk"
          sudo wget "https://github.com/2dust/v2rayNG/releases/download/1.8.39/v2rayNG_1.8.39_universal.apk"
          sudo wget "https://github.com/2dust/v2rayNG/releases/download/1.8.39/v2rayNG_1.8.39_x86.apk"
          sudo wget "https://github.com/2dust/v2rayNG/releases/download/1.8.39/v2rayNG_1.8.39_x86_64.apk"
          tree ./

      - name: Upload to Release
        uses: svenstaro/upload-release-action@v2
        with:
          body: |
              Cuma buat nyimpen doang
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: ./*.apk
          release_name: APK Release
          tag: 1.0.5
          file_glob: true
          overwrite: true
