name: Subscription Updater

on:
  push:
    branches: [ "main" ]
  schedule:
    - cron: '*/90 * * * *'

  #workflow_dispatch:
jobs:
  UpdateSub:
    runs-on: ubuntu-latest

    steps:
      - name: Check The Code
        uses: actions/checkout@v2
      - name: Get Files
        run: |
          curl -o aktif.txt -LJO "https://raw.githubusercontent.com/MrMohebi/xray-proxy-grabber-telegram/master/collected-proxies/row-url/actives.txt"
          curl -o semua.txt -LJO "https://raw.githubusercontent.com/MrMohebi/xray-proxy-grabber-telegram/master/collected-proxies/row-url/all.txt"
          curl -o kumpulan-p1.txt -LJO "https://raw.githubusercontent.com/LalatinaHub/Mineral/master/result/nodes"
          curl -o kumpulan-p2.txt -LJO "https://raw.githubusercontent.com/hkpc/V2ray-Configs/main/Splitted-By-Protocol/vmess.txt"
          curl -o kumpulan-p3.txt -LJO "https://github.com/Surfboardv2ray/TGParse/raw/main/configtg.txt"
          curl -o subapi -LJO "https://raw.githubusercontent.com/mahdibland/V2RayAggregator/master/sub/sub_merge_base64.txt"
          curl -o v2tel_link.txt -LJO "https://raw.githubusercontent.com/SamanGho/v2ray_collector/main/v2tel_link.txt"
          curl -o v2tel_links1.txt -LJO "https://raw.githubusercontent.com/SamanGho/v2ray_collector/main/v2tel_links1.txt"
          curl -o v2tel_links2.txt -LJO "https://raw.githubusercontent.com/SamanGho/v2ray_collector/main/v2tel_links2.txt"
          curl -o cm1.yml -LJO "https://raw.githubusercontent.com/snakem982/proxypool/main/source/clash-meta.yaml"
          curl -o cm2.yml -LJO "https://raw.githubusercontent.com/snakem982/proxypool/main/source/clash-meta-1.yaml"
          curl -o cm3.yml -LJO "https://raw.githubusercontent.com/snakem982/proxypool/main/source/clash-meta-2.yaml"
          curl -o tgproxy.txt -LJO "https://raw.githubusercontent.com/V2RAYCONFIGSPOOL/TELEGRAM_PROXY_SUB/main/TELEGRAM_PROXY.txt"      
          curl -o merge24.txt -LJO "https://github.com/9Knight9n/v2ray-aggregator/raw/main/merged_24h.txt"      
          curl -o singbox.json -LJO "https://raw.githubusercontent.com/Mahdi0024/ProxyCollector/master/sub/singbox.json"      
          curl -o nekobox.txt -LJO "https://raw.githubusercontent.com/Mahdi0024/ProxyCollector/master/sub/proxies.txt"
          curl -o sub-all -LJO "https://raw.githubusercontent.com/yebekhe/V2Hub/refs/heads/main/merged"
          curl -o sub-reality -LJO "https://raw.githubusercontent.com/yebekhe/V2Hub/refs/heads/main/Split/Normal/reality"
          curl -o sub-ss -LJO "https://raw.githubusercontent.com/yebekhe/V2Hub/refs/heads/main/Split/Normal/shadowsocks"
          curl -o sub-trojan -LJO "https://raw.githubusercontent.com/yebekhe/V2Hub/refs/heads/main/Split/Normal/trojan"
          curl -o sub-vless -LJO "https://raw.githubusercontent.com/yebekhe/V2Hub/refs/heads/main/Split/Normal/vless"
          curl -o sub-vmess -LJO "https://raw.githubusercontent.com/yebekhe/V2Hub/refs/heads/main/Split/Normal/vmess"
          curl -o all_$(TZ='Asia/Jakarta' date '+%Y-%m-%d') -LJO "https://raw.githubusercontent.com/yebekhe/V2Hub/refs/heads/main/merged"
          curl -o reality_$(TZ='Asia/Jakarta' date '+%Y-%m-%d') -LJO "https://raw.githubusercontent.com/yebekhe/V2Hub/refs/heads/main/Split/Normal/reality"
          curl -o ss_$(TZ='Asia/Jakarta' date '+%Y-%m-%d') -LJO "https://raw.githubusercontent.com/yebekhe/V2Hub/refs/heads/main/Split/Normal/shadowsocks"
          curl -o trojan_$(TZ='Asia/Jakarta' date '+%Y-%m-%d') -LJO "https://raw.githubusercontent.com/yebekhe/V2Hub/refs/heads/main/Split/Normal/trojan"
          curl -o vless_$(TZ='Asia/Jakarta' date '+%Y-%m-%d') -LJO "https://raw.githubusercontent.com/yebekhe/V2Hub/refs/heads/main/Split/Normal/vless"
          curl -o vmess_$(TZ='Asia/Jakarta' date '+%Y-%m-%d') -LJO "https://raw.githubusercontent.com/yebekhe/V2Hub/refs/heads/main/Split/Normal/vmess"

      - name: Push And Update Files
        run: |
          git config --global user.name "dinaneq"
          git config --global user.email "dinanda@5412.us.to"
          git add .
          git commit -m "Diperbarui pada - $(TZ='Asia/Jakarta' date '+%Y-%m-%d %H:%M:%S') WIB"
          git push
